### ISSUE TITLE
Feature: add language japanese

### ISSUE THREAD

**Issue by ryuushihou** [fastjs-team/fastjs.cc#12]
### What is the feature?

Add Japanese version to homepage

### Why is this feature needed?

for internationalization

### Confirmations

- [X] I have read the [Code of Conduct](https://docs.fastjs.cc/other/code-of-conduct.html)
- [X] I have read the [Issue Reporting Guidelines](https://github.com/fastjs-team/core/blob/main/.github/contributing.md#issue-reporting)
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] I know that any inappropriate content may cause the maintainer to take action base on the [Code of Conduct](https://docs.fastjs.cc/other/code-of-conduct.html)
- [ ] This feature request is open because to fix a bug/issue

**Comment by dy-xiaodong2022** [comment]
Sure, but we will do this later, you can open a Pull Request if you want to do it yourself too.
