### ISSUE TITLE
Fix：Remove extra semicolons causing compilation errors

### ISSUE THREAD

**Issue by ryuushihou** [fastjs-team/fastjs.cc#13]
### What is the current behavior?

![image](https://github.com/fastjs-team/fastjs.cc/assets/113272024/f15d1564-659a-49d4-ab42-8e4d72354756)

### What is the expected behavior?

Resolve compilation errors

### Steps to reproduce the problem

open src/components/topbar/topbar.vue
or
run eslint

### Confirmations

- [X] I have read the [Code of Conduct](https://docs.fastjs.cc/other/code-of-conduct.html)
- [X] I have read the [Issue Reporting Guidelines](https://github.com/fastjs-team/core/blob/main/.github/contributing.md#issue-reporting)
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] I know that any inappropriate content may cause the maintainer to take action base on the [Code of Conduct](https://docs.fastjs.cc/other/code-of-conduct.html)

**Comment by dy-xiaodong2022** [comment]
Try to update your local branch.

**Comment by ryuushihou** [comment]
@dy-xiaodong2022  already updated but fastjs main branch is this：
<img width="1311" alt="image" src="https://github.com/fastjs-team/fastjs.cc/assets/113272024/1d3eac8d-90ff-4fbb-bd24-bdec8b1bfa5f">

**Comment by dy-xiaodong2022** [comment]
Thank you, this problem has been fixed at 6ffcab9e28456231f997f322e266927508fbd56f
